# Generated by Django 5.1.4 on 2025-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_text', models.TextField()),
                ('project_link', models.TextField(default='')),
                ('project_image', models.ImageField(upload_to='projects')),
                ('project_type', models.CharField(choices=[('PERSONAL', 'Personel'), ('PROFESSIONAL', 'Professionel'), ('FORMATION', 'Formation')], default='PERS', max_length=100)),
                ('project_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
