# Generated by Django 5.1.5 on 2025-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_client',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_github_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_short_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=models.TextField(default=''),
        ),
    ]
