# Generated by Django 5.1.5 on 2025-05-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_project_client_project_project_github_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('profile_description', models.TextField(default='')),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('profile_stack', models.ManyToManyField(to='myapp.stack')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_enterprise', models.CharField(max_length=100)),
                ('xp_start_date', models.DateField()),
                ('xp_end_date', models.DateField(blank=True, null=True)),
                ('xp_description', models.TextField()),
                ('xp_stack', models.ManyToManyField(to='myapp.stack')),
            ],
        ),
    ]
