# Generated by Django 5.1.5 on 2025-05-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_stack_alter_project_project_date_profile_experiences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiences',
            old_name='xp_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='xp_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='xp_enterprise',
            new_name='enterprise',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='xp_stack',
            new_name='stack',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='xp_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_stack',
            new_name='stack',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_github_link',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_short_text',
            new_name='short_text',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='stack',
            old_name='stack_name',
            new_name='name',
        ),
    ]
